### Get all currencies
GET http://localhost:8080/currency_exchange_war_exploded/currencies
Accept: application/json

### Get currency
GET http://localhost:8080/currency_exchange_war_exploded/currency/USD
Accept: application/json

### Add a new currency
POST http://localhost:8080/currency_exchange_war_exploded/currencies?
    code=USD&
    name=US dollar&
    sign=@
Content-Type: application/json

### Get all exchange rates
GET http://localhost:8080/currency_exchange_war_exploded/exchangeRates
Accept: application/json

### Get exchange rate USD → EUR
GET http://localhost:8080/currency_exchange_war_exploded/exchangeRate/USDEUR
Content-Type: application/json

### Add new exchange rate
POST http://localhost:8080/currency_exchange_war_exploded/exchangeRates
Content-Type: application/x-www-form-urlencoded

baseCurrencyCode=JPY&
targetCurrencyCode=USD&
rate=90

### Update exchange rate USD → EUR
PATCH http://localhost:8080/currency_exchange_war_exploded/exchangeRate/USDEUR
Content-Type: application/x-www-form-urlencoded

rate=0.88

### Exchange from -> to
GET http://localhost:8080/currency_exchange_war_exploded/exchange?from=USD&to=EUR&amount=107897789.00
Content-Type: application/json





